# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V36z6tJtaEzYg-7r6EiLVeUUZQLTpNiN

# Import Library
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""# Import data"""

df = pd.read_csv("main_data.csv")

"""# Set up Streamlit"""

st.set_page_config(
    page_title="Proyek Akhir Bike Analysis",
    page_icon=":sparkles:",
    layout="wide"
)

sns.set_style("whitegrid")

"""## Create Dashboard"""

# Create title
st.title("Bike Sharing Data Analysis Dashboard :bicycle: ")

st.header("Statistic Summary of Data")

total_rental = df["total_rental"].sum()
average_daily_rental = df["total_rental"].mean()

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    label="Total Rental",
    value=f"{total_rental:,}"
)

col2.metric(
    label="Average Daily Bike Rental",
    value=f"{average_daily_rental:,}"
)

lowest_season = (
    df.groupby("season")["total_rental"].mean().idxmin()
)

highest_season = (
    df.groupby("season")["total_rental"].mean().idxmax()
)

col3.metric("Season with Lowest Average Bike Rental",
             lowest_season
)

col4.metric("Season with Highest Average Bike Rental",
             highest_season)

"""# Pertanyaan 1"""

# Pertanyaan 1
st.header("Pertanyaan 1")

df_pivot_1 = (df.groupby(["season", "weather"]).agg(
    average_daily_rental=("total_rental", "mean")
).reset_index().round(3)
)

fig,ax = plt.subplots(figsize=(10,5))

sns.barplot(
    data=df_pivot_1,
    x="season",
    y="average_daily_rental",
    hue="weather",
    ax=ax
)

ax.set_xlabel("Season")
ax.set_ylabel("Average Daily Bike Rental")
ax.set_title("Average Bike Rentals Counts based on Weather and Season")

st.pyplot(fig)
st.caption("Rata-rata permintaan sewa sepeda saat cuaca Light Rain/Light Snow di musim Spring paling rendah di antara kombinasi lainnya")

"""# Pertanyaan 2"""

# Pertanyaan 2
st.header("Pertanyaan 2")

st.write("Pertanyaan 2")

df_2012 = df[df["year"]=="2012"]

# Memastikan bulan yang ditampilkan urut dari Januari - Desember
order_month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

df_2012["month"] = pd.Categorical(df["month"],
                                  categories=order_month,
                                  ordered=True)
df_2012 = df_2012.sort_values("month")

# Create pivot table
df_pivot_2 = (df_2012.groupby(["month", "workingday_type"])
.agg(average_daily_rental=("total_rental","mean"))
.reset_index().round(3)
)

# Visualize
fig, ax = plt.subplots(figsize=(15,8))

sns.lineplot(
    data=df_pivot_2,
    x="month",
    y="average_daily_rental",
    hue="workingday_type",
    marker="o",
    width=3.0,
    ax=ax
)

ax.set_title("Trends of Average Daily Bike Rental for Working Day and Non-Working Day in 2012")
plt.xlabel("Month")
plt.ylabel("Average Daily Bike Rental")

plt.xticks(rotation=45)

st.pyplot(fig)
st.caption("Nilai rata-rata permintaan sewa sepeda pada tahun 2012 cenderung lebih tinggi untuk Working Days dibandingkan Non-Working Days, dengan bulan tertinggi untuk permintaan sewa sepeda di bulan September")

st.header("Dataset Preview")
st.dataframe(df)
st.write(f"Total Observations: **{len(df):,}**")