# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V36z6tJtaEzYg-7r6EiLVeUUZQLTpNiN
"""


# Import Library
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import data
from pathlib import Path
base_dir = Path(__file__).resolve().parent
data_file = base_dir/"main_data.csv"
df = pd.read_csv(data_file)


# Create Dashboard
st.set_page_config(
    page_title="Proyek Akhir Bike Analysis",
    page_icon=":sparkles:",
    layout="wide"
)

sns.set_style("whitegrid")

# Create Filter
st.sidebar.header("Filter By")

year_options = st.sidebar.multiselect("Select Year",
                                      options=sorted(df["year"].unique()),
                                      default=sorted(df["year"].unique())
                                     )

season_options = st.sidebar.multiselect("Select Season",
                                       options=sorted(df["season"].unique()),
                                       default=sorted(df["season"].unique())
                                      )

weather_options = st.sidebar.multiselect("Select Weather",
                                         options=sorted(df["weather"].unique()),
                                         default=sorted(df["weather"].unique())
                                        )

month_options = st.sidebar.multiselect("Select Month",
                                       options=sorted(df["month"].unique()),
                                       default=sorted(df["month"].unique())
                                      )

df_copy = df[(df["year"].isin(year_options)) &
(df["season"].isin(season_options)) &
(df["weather"].isin(weather_options)) &
(df["month"].isin(month_options))
]

selected_year = ", ".join(map(str, year_options))
selected_season = ", ".join(map(str, season_options))
selected_weather = ", ".join(map(str, weather_options))
selected_month = ", ".join(map(str, month_options))

# Create title
st.title("Bike Sharing Data Analysis Dashboard")

st.header("Statistic Summary of Data")

total_rental = df["total_rental"].sum()
average_daily_rental = df["total_rental"].mean()

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    label="Total Rental",
    value=f"{total_rental:,}"
)

col2.metric(
    label="Average Daily Bike Rental",
    value=f"{average_daily_rental:,}"
)

lowest_season = (
    df.groupby("season")["total_rental"].mean().idxmin()
)

highest_month = (
    df.groupby("month")["total_rental"].mean().idxmax()
)

col3.metric("Season with Lowest Average Bike Rental",
             lowest_season
)

col4.metric("Month with Highest Average Bike Rental",
             highest_month)

st.header("Bike Rental Data Preview")
st.dataframe(df)
st.write(f"Total Observations: **{len(df):,}**")

# Pertanyaan 1
st.header("Pengaruh Kombinasi Cuaca dan Musim Terhadap Nilai Rata-rata Permintaan Sewa Sepeda")
st.caption(f"Clustered Bar Chart tahun : **{selected_year}**, musim : **{selected_season}**")

df_pivot_1 = (df_copy.groupby(["season", "weather"]).agg(
    average_daily_rental=("total_rental", "mean")
).reset_index().round(3)
)

fig,ax = plt.subplots(figsize=(10,5))

sns.barplot(
    data=df_pivot_1,
    x="season",
    y="average_daily_rental",
    hue="weather",
    ax=ax
)

ax.set_xlabel("Season")
ax.set_ylabel("Average Daily Bike Rental")
ax.set_title("Average Bike Rentals Counts based on Weather and Season")
ax.legend(
    title="Weather",
    loc="upper left",
    bbox_to_anchor=(1.0, 1.0),
    ncol=1
)


st.pyplot(fig)
st.caption("Rata-rata permintaan sewa sepeda antara tahun 2011-2012 saat cuaca Light Rain/Light Snow di musim Spring paling rendah di antara kombinasi cuaca dan musim lainnya. Sementara itu, cuaca Clear/Partly Cloud di bulan Autumn merupakan kondisi paling ideal untuk menyewa sepeda")

# Pertanyaan 2
st.header("Pengaruh Working Day dan Non-Working Day terhadap Rata-rata Permintaan Sewa Sepeda")
st.caption("Line chart ini hanya akan menampilkan untuk pilihan tahun 2012, atau pilihan kedua tahun")
st.caption(f"Menampilkan data untuk bulan : **{selected_month}**")

df_2012 = df[df["year"]==2012]

# Create pivot table
df_pivot_2 = (df_2012.groupby(["month", "workingday_type"])
.agg(average_daily_rental=("total_rental", "mean"))
.reset_index().round(3))

# Memastikan bulan yang ditampilkan urut dari Januari - Desember
order_month = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

df_pivot_2["month"] = pd.Categorical(df_pivot_2["month"],
                                  categories=order_month,
                                  ordered=True)
df_pivot_2 = df_pivot_2.sort_values("month")

# Visualize
fig, ax = plt.subplots(figsize=(15,8))

sns.lineplot(
    data=df_pivot_2,
    x="month",
    y="average_daily_rental",
    hue="workingday_type",
    marker="o",
    ax=ax
)

ax.set_title("Trends of Average Daily Bike Rental for Working Day and Non-Working Day in 2012")
plt.xlabel("Month")
plt.ylabel("Average Daily Bike Rental")

plt.xticks(rotation=45)

st.pyplot(fig)
st.caption("Nilai rata-rata permintaan sewa sepeda pada tahun 2012 cenderung lebih tinggi untuk Working Days dibandingkan Non-Working Days, dengan bulan tertinggi untuk permintaan sewa sepeda di bulan September")
